### ISSUE TITLE
Text RTL

### ISSUE THREAD

**Issue by shalomda** [mojtabakaviani/bootstrap-rtl#14]
Hi, first of all great job man!

The text is not from right to left
1. I need to add text-right class to change the position of the text
2. The dot (.) in the end of paragraph or sentence is float to right side and not to the left side near the end word.

Maybe we need to add direction:rtl in the body or something else?

**Comment by mojtabakaviani** [comment]
For use bootstrap-rtl  must add `dir="rtl"` to html tag.

**Comment by shalomda** [comment]
Thanks
