### ISSUE TITLE
Nuget folder structure

### ISSUE THREAD

**Issue by HarelM** [mojtabakaviani/bootstrap-rtl#5]
Hi,

I'm not sure if this is intended or not, but the folder stucture is different from the regular bootstrap in nuget.
The folder structure of regular bootstrap is:
- content (for css)
- fonts (for fonts)
- scripts (for java scripts)

The folder structure of this package is:
- content (for css)
-- fonts (inside content and not as a seperate folder)
- scripts

I'm using both packages side by side in order to switch between trl and ltr.
BTW, do I need both fonts folders from regular bootstrap and bootstrap trl?

Thanks,
Harel M.

**Comment by mojtabakaviani** [comment]
We change folders structure in new version 3.3.5-rc1
thanks.
