### ISSUE TITLE
How was this RTL version created?

### ISSUE THREAD

**Issue by OsamaAbbas** [mojtabakaviani/bootstrap-rtl#8]
Hi,

Could you please show us the method that was used to create RTL version of Bootstrap?

**Comment by mojtabakaviani** [comment]
I created RTL version manual and test in real project. so can create RTL with script but not work perfectly.

**Comment by OsamaAbbas** [comment]
Wow. This is a great effort!
Unfortunately, I still need an automated method because I have some modified version of Bootstrap.
This tool [RTLCSS](https://github.com/MohammadYounes/rtlcss) is very good so far. Still testing it.
